Lint with Trunk

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,49 +2,49 @@
 
 set -euo pipefail
 
-[ -z "${ASDF_INSTALL_TYPE+x}" ] && echo "ASDF_INSTALL_TYPE is required" && exit 1
-[ -z "${ASDF_INSTALL_VERSION+x}" ] && echo "ASDF_INSTALL_VERSION is required" && exit 1
-[ -z "${ASDF_INSTALL_PATH+x}" ] && echo "ASDF_INSTALL_PATH is required" && exit 1
+[[ -z ${ASDF_INSTALL_TYPE+x} ]] && echo "ASDF_INSTALL_TYPE is required" && exit 1
+[[ -z ${ASDF_INSTALL_VERSION+x} ]] && echo "ASDF_INSTALL_VERSION is required" && exit 1
+[[ -z ${ASDF_INSTALL_PATH+x} ]] && echo "ASDF_INSTALL_PATH is required" && exit 1
 
 install() {
-  local install_type=$1
-  [ "$install_type" != "version" ] && echo "intall type, $install_type, is not supported" && exit 1
+	local install_type=$1
+	[[ ${install_type} != "version" ]] && echo "intall type, ${install_type}, is not supported" && exit 1
 
-  local version=$2
-  local install_path=$3
+	local version=$2
+	local install_path=$3
 
-  local bin_install_path="$install_path/bin"
+	local bin_install_path="${install_path}/bin"
 
-  local platform
-  platform=$(uname | tr '[:upper:]' '[:lower:]')
-  case "$platform" in
-    darwin) platform="macos";;
-  esac
+	local platform
+	platform=$(uname | tr '[:upper:]' '[:lower:]')
+	case "${platform}" in
+	darwin) platform="macos" ;;
+	esac
 
-  local arch
-  arch=$(uname -m)
-  case "$arch" in
-    x86_64) arch="amd64";;
-    aarch64) arch="arm64";;
-  esac
+	local arch
+	arch=$(uname -m)
+	case "${arch}" in
+	x86_64) arch="amd64" ;;
+	aarch64) arch="arm64" ;;
+	esac
 
-  local download_url
-  download_url="https://github.com/databus23/helm-diff/releases/download/v${version}/helm-diff-${platform}-${arch}.tgz"
-  case "$version" in
-    3.[01].*|[012].*) download_url="https://github.com/databus23/helm-diff/releases/download/v${version}/helm-diff-${platform}.tgz";;
-  esac
+	local download_url
+	download_url="https://github.com/databus23/helm-diff/releases/download/v${version}/helm-diff-${platform}-${arch}.tgz"
+	case "${version}" in
+	3.[01].* | [012].*) download_url="https://github.com/databus23/helm-diff/releases/download/v${version}/helm-diff-${platform}.tgz" ;;
+	esac
 
-  mkdir -p "${bin_install_path}"
+	mkdir -p "${bin_install_path}"
 
-  echo "Downloading helm-diff from ${download_url}"
+	echo "Downloading helm-diff from ${download_url}"
 
-  pushd "${bin_install_path}" > /dev/null
+	pushd "${bin_install_path}" >/dev/null
 
-  curl -sL "$download_url" | tar zx -O diff/bin/diff > "${bin_install_path}/helm-diff"
+	curl -sL "${download_url}" | tar zx -O diff/bin/diff >"${bin_install_path}/helm-diff"
 
-  chmod +x "${bin_install_path}/helm-diff"
+	chmod +x "${bin_install_path}/helm-diff"
 
-  cat > "${install_path}/plugin.yaml" << END
+	cat >"${install_path}/plugin.yaml" <<END
 name: "diff"
 version: "asdf"
 usage: "Preview helm upgrade changes as a diff"
@@ -52,13 +52,13 @@ description: "Preview helm upgrade changes as a diff"
 useTunnel: true
 command: "helm-diff"
 END
-  ln -s . "${install_path}/helm-diff"
+	ln -s . "${install_path}/helm-diff"
 
-  popd > /dev/null
+	popd >/dev/null
 
-  if command -v helm >/dev/null && ! helm plugin list | sed 1d | grep -qs '^diff[[:space:]]'; then
-    helm plugin install "${install_path}/helm-diff" || true
-  fi
+	if command -v helm >/dev/null && ! helm plugin list | sed 1d | grep -qs '^diff[[:space:]]'; then
+		helm plugin install "${install_path}/helm-diff" || true
+	fi
 }
 
-install "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install "${ASDF_INSTALL_TYPE}" "${ASDF_INSTALL_VERSION}" "${ASDF_INSTALL_PATH}"
